data_cfg:
  train_images_root: /mnt/8TB/cvlab/DATA/FocusPath_DATA/FocusPath_full_merged
  val_images_root: /mnt/8TB/cvlab/DATA/FocusPath_DATA/FocusPath_full_merged
  test_images_root: /mnt/8TB/cvlab/DATA/FocusPath_DATA/FocusPath_full_merged
  train_data_file: /mnt/8TB/cvlab/DATA/FocusPath_DATA/FocusPath_full_merged/data_list/FocusPath_train_database.txt
  val_data_file: /mnt/8TB/cvlab/DATA/FocusPath_DATA/FocusPath_full_merged/data_list/FocusPath_val_database.txt
  test_data_file: /mnt/8TB/cvlab/DATA/FocusPath_DATA/FocusPath_full_merged/data_list/FocusPath_val_database.txt
runner_cfg:
  model_cfg:
    prompt_learner_cfg:
      num_ranks: 12
