data_cfg:
  train_images_root: /mnt/8TB/cvlab/DATA/BBBC006_DATA/BBBC006
  val_images_root: /mnt/8TB/cvlab/DATA/BBBC006_DATA/BBBC006
  test_images_root: /mnt/8TB/cvlab/DATA/BBBC006_DATA/BBBC006
  train_data_file: /mnt/8TB/cvlab/DATA/BBBC006_DATA/BBBC006/data_list/BBBC006_train_database.txt
  val_data_file: /mnt/8TB/cvlab/DATA/BBBC006_DATA/BBBC006/data_list/BBBC006_val_database.txt
  test_data_file: /mnt/8TB/cvlab/DATA/BBBC006_DATA/BBBC006/data_list/BBBC006_val_database.txt
runner_cfg:
  model_cfg:
    prompt_learner_cfg:
      num_ranks: 10
      num_context_tokens: 20
      rank_tokens_position: middle
      stain_tokens_position: tail